import { PDFDocument } from "pdf-lib";
import type { DpProjectRecord, DpSourceFile } from "@/lib/dp-pdf";
import { CONFORMITY_POLICY_VERSION } from "@/lib/conformity-policy";
import { resolveVerifiedPvModule } from "@/lib/pv-module-catalog";

export type GateIssue = {
  code: string;
  message: string;
  field?: string;
};

export const requiredSourceKinds = [
  "satellite",
  "satellite_mass",
  "near",
  "roof",
  "far",
] as const;

const requiredDetailFields = [
  "cadastralReference",
  "parcelAreaM2",
  "parcelGeometry",
  "urbanismDocumentId",
  "urbanismDocumentType",
  "urbanismZone",
  "urbanismRuleSourceUrl",
  "urbanismCheckedAt",
  "municipality",
  "satelliteAutoGenerated",
  "satelliteSourceUrl",
  "satelliteMetersPerPixel",
  "satelliteGeneratedAt",
  "satelliteMassSourceUrl",
  "satelliteMassMetersPerPixel",
  "satelliteMassGeneratedAt",
  "panelGapMm",
] as const;

export function validateGenerationInputs(
  project: DpProjectRecord,
  sources: DpSourceFile[],
  finalAttestation: boolean,
) {
  const issues: GateIssue[] = [];
  const sourceByKind = new Map(sources.map((source) => [source.kind, source]));

  if (!project.requesterName.trim()) issues.push({ code: "REQUESTER", field: "requesterName", message: "Identité du demandeur absente." });
  if (!project.siteAddress.trim()) issues.push({ code: "SITE", field: "siteAddress", message: "Adresse du projet absente." });
  if (!project.moduleCount || project.moduleCount < 1) issues.push({ code: "MODULE_COUNT", field: "moduleCount", message: "Nombre de modules invalide." });
  if (!project.moduleReference.trim()) {
    issues.push({ code: "MODULE_REFERENCE", field: "moduleReference", message: "Référence des modules absente." });
  } else if (!resolveVerifiedPvModule(project.moduleReference)) {
    issues.push({
      code: "MODULE_REFERENCE_UNKNOWN",
      field: "moduleReference",
      message: "La référence du module n'est pas présente dans le catalogue fabricant vérifié. Ajoutez sa fiche technique fabricant avant génération.",
    });
  }
  if (!["roof", "carport", "canopy", "flat_roof"].includes(project.supportType)) issues.push({ code: "SUPPORT_NOT_IMPLEMENTED", field: "supportType", message: "Support non pris en charge par le nouveau moteur photovoltaïque." });

  requiredDetailFields.forEach((field) => {
    if (!project.details[field]?.trim()) {
      issues.push({ code: "DETAIL", field, message: `Information technique manquante : ${field}.` });
    }
  });

  if (project.details.satelliteAutoGenerated !== "true") {
    issues.push({ code: "SATELLITE_ORIGIN", field: "satellite", message: "La vue satellite n’a pas été générée automatiquement par PilotPaper." });
  }
  try {
    const satelliteUrl = new URL(project.details.satelliteSourceUrl ?? "");
    if (satelliteUrl.protocol !== "https:" || satelliteUrl.hostname !== "data.geopf.fr") throw new Error();
  } catch {
    issues.push({ code: "SATELLITE_SOURCE", field: "satellite", message: "La provenance officielle IGN de la vue satellite n’est pas démontrée." });
  }
  const metersPerPixel = Number(project.details.satelliteMetersPerPixel);
  if (!Number.isFinite(metersPerPixel) || metersPerPixel <= 0 || metersPerPixel > 1) {
    issues.push({ code: "SATELLITE_SCALE", field: "satellite", message: "L’échelle métrique de la vue satellite est invalide." });
  }
  try {
    const satelliteMassUrl = new URL(project.details.satelliteMassSourceUrl ?? "");
    if (satelliteMassUrl.protocol !== "https:" || satelliteMassUrl.hostname !== "data.geopf.fr") throw new Error();
  } catch {
    issues.push({ code: "SATELLITE_MASS_SOURCE", field: "satellite_mass", message: "La provenance officielle IGN de la vue rapprochée n’est pas démontrée." });
  }
  const massMetersPerPixel = Number(project.details.satelliteMassMetersPerPixel);
  if (!Number.isFinite(massMetersPerPixel) || massMetersPerPixel <= 0 || massMetersPerPixel >= metersPerPixel) {
    issues.push({ code: "SATELLITE_MASS_SCALE", field: "satellite_mass", message: "La vue de plan de masse n’est pas plus précise que le plan de situation." });
  }

  requiredSourceKinds.forEach((kind) => {
    if (!sourceByKind.has(kind)) {
      issues.push({ code: "SOURCE_MISSING", field: kind, message: `Source contrôlée manquante : ${kind}.` });
    }
  });

  for (const kind of ["satellite", "satellite_mass", "near", "roof", "far"] as const) {
    const source = sourceByKind.get(kind);
    if (source && !["image/jpeg", "image/png"].includes(source.mimeType)) {
      issues.push({ code: "PHOTO_FORMAT", field: kind, message: `${kind} doit être une photographie JPEG ou PNG.` });
    }
  }

  if (sources.length !== 5 || new Set(sources.map((source) => source.kind)).size !== 5) {
    issues.push({ code: "SOURCE_SET", field: "photos", message: "Deux vues IGN automatiques et trois photographies utilisateur distinctes (proche, oblique toiture, lointaine) sont requises." });
  }
  if (new Set(sources.map((source) => source.sha256)).size !== sources.length) {
    issues.push({ code: "SOURCE_DUPLICATE", field: "photos", message: "Deux vues possèdent la même empreinte et ne sont pas des preuves indépendantes." });
  }

  const urbanismCheckedAt = Date.parse(project.details.urbanismCheckedAt ?? "");
  if (!Number.isFinite(urbanismCheckedAt) || Date.now() - urbanismCheckedAt > 30 * 24 * 60 * 60 * 1000 || urbanismCheckedAt > Date.now() + 5 * 60 * 1000) {
    issues.push({ code: "URBANISM_STALE", field: "siteAddress", message: "La consultation officielle des règles d’urbanisme est absente ou date de plus de 30 jours." });
  }
  if (project.details.urbanismAuthorityReviewRequired === "true") {
    issues.push({ code: "AUTHORITY_REVIEW_REQUIRED", field: "siteAddress", message: "Une protection patrimoniale impose une appréciation d’autorité que PilotPaper ne peut pas remplacer." });
  }

  if (!finalAttestation) {
    issues.push({ code: "ATTESTATION", field: "finalAttestation", message: "L’attestation finale de contrôle n’a pas été confirmée." });
  }

  return issues;
}

export async function validateGeneratedPdf(bytes: Uint8Array) {
  const issues: GateIssue[] = [];
  try {
    const pdf = await PDFDocument.load(bytes);
    if (pdf.getPageCount() < 31) {
      issues.push({ code: "PDF_PAGE_COUNT", message: "Le dossier généré ne contient pas assez de pages contrôlables." });
    }
    const title = pdf.getTitle() ?? "";
    if (!title.toLowerCase().includes("declaration prealable")) {
      issues.push({ code: "PDF_METADATA", message: "Les métadonnées du dossier sont incomplètes." });
    }
    const rawKeywords = pdf.getKeywords();
    const keywords = Array.isArray(rawKeywords) ? rawKeywords.join(" ") : rawKeywords ?? "";
    if (!keywords.includes(CONFORMITY_POLICY_VERSION)) {
      issues.push({ code: "PDF_POLICY", message: "Le PDF ne référence pas la politique de conformité active." });
    }
    const form = pdf.getForm();
    for (const fieldName of ["T2V_voie", "T2C_code", "T2S_section", "T2N_numero", "C2ZD1_description", "E1S_signature"]) {
      if (!form.getTextField(fieldName).getText()?.trim()) {
        issues.push({ code: "CERFA_FIELD", field: fieldName, message: `Le champ officiel ${fieldName} n’est pas rempli.` });
      }
    }
    for (const fieldName of ["P5PA2", "P5PB1", "P3GE1", "P3GD1", "P5PC1", "P3GF1", "P3GG1", "P3GH1"]) {
      if (!form.getCheckBox(fieldName).isChecked()) {
        issues.push({ code: "CERFA_ATTACHMENT", field: fieldName, message: `La pièce ${fieldName} n’est pas cochée dans le bordereau officiel.` });
      }
    }
  } catch {
    issues.push({ code: "PDF_INVALID", message: "Le fichier produit n’est pas un PDF lisible." });
  }
  return issues;
}
